[package]
name = "kizuna"
version = "0.1.0"
edition = "2024"

[dependencies]
logc = "0.3.3"
rustls = "0.23.28"
rustls-pemfile = "2.2.0"
tokio = { version = "1.45.1", features = ["full"] }
tokio-rustls = "0.26.2"
