name: C/C++ CI

on:
  push:
    branches: [ "master", "release" ]
  pull_request:
    branches: [ "master", "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run make
      run: make release
    - name: install openssl dev libs
      run: sudo apt-get update && sudo apt-get install -y libssl-dev 
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: kizuna
        path: ./build/kizuna
